name: test

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.5
          extensions: mbstring
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer install -q
      - name: env
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Test
        run: vendor/bin/phpunit
      - name: Code Coverage
        uses: qltysh/qlty-action/coverage@a2277a908db90c4c868832fb9204521fb940fdb4 # v1
        with:
          oidc: true
          files: build/logs/clover.xml
