name: test

on:
  push:
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.4
          extensions: mbstring
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer install -q
      - name: env
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Test
        run: vendor/bin/phpunit
      - name: Code Coverage
        uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: build/logs/clover.xml
      - name: forge
        if: success() && (github.event_name != 'pull_request')
        run: curl -s ${{ secrets.FORGE }}
